### ISSUE TITLE
es search default number of hits returned

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bbconf#3]
@stolarczyk I completely forgot a small but important detail. If I recall correctly the `bbconf search_bedfiles` function is a wrapper of `es.search()` right? The problem is that this function defaults the number of returned hits to 10, regardless of how many files exist in a certain index. So as of now if we had hundreds of file in the `bedfiles` index, `bedbuncher` would only process 10.

It might be a really easy fix, `es.search()` has the argument `size` (default:10) which allows you to define the number of desired returned hits. https://elasticsearch-py.readthedocs.io/en/master/api.html

**Comment by stolarczyk** [comment]
I made it return all the hits on dev branch last week. I’ll probs make a release tomorrow, so use the dev version for now

**Comment by stolarczyk** [comment]
000f5fcf44bc124a87affbd90552da5ca22dce08

**Comment by joseverdezoto** [comment]
Gotcha!
