### ISSUE TITLE
Sentence transformer update to fastembed?

### ISSUE THREAD

**Issue by nsheff** [databio/bbconf#35]
```
File "/usr/local/lib/python3.11/site-packages/bbconf/bbconf.py", line 49, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
```

But in fact, it appears that geniml is no longer using SentenceTransformer.

@ClaudeHu, can you update these two lines to accommodate the new way of using the text2bednn in your dev geniml branch?

- https://github.com/databio/bbconf/blob/dev/bbconf/bbconf.py#L49

- https://github.com/databio/bbconf/blob/dev/bbconf/bbconf.py#L510

**Comment by nsheff** [comment]
@nleroy917 should it be possible then to have bbconf not require torch?

how will we organize this?

**Comment by khoroshevskyi** [comment]
@ClaudeHu I think this is Geniml issue, am I correct? If yes, please, transfer this issue to geniml

**Comment by ClaudeHu** [comment]
> @ClaudeHu I think this is Geniml issue, am I correct? If yes, please, transfer this issue to geniml

Not completely a `geniml` issue. `geniml` had an update (replace `SentenceTransformers` by `fastembed`) and code here was not adjusted. Now `bbconf/bbconf.py` has been adjusted for that refactor.

**Comment by khoroshevskyi** [comment]
@ClaudeHu what do you think, how long will it take to finish this issue? Can you take the lead on this issue, and when it will be solved write it here?

**Comment by khoroshevskyi** [comment]
This issue was fixed by @ClaudeHu
