### ISSUE TITLE
Should bbconf be renamed to bbagent ? 

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bbconf#40]
Me and @donaldcampbelljr thought, what if bbconf will be renamed bbagent to have similar standard naming (like pepdbagent)?
Additionally, it will be easier to distinguish bbclient and bbconf

**Comment by nsheff** [comment]
Probably not. bbconf is parallel to refgenconf. I guess to standardize we could rename pepdbagent to pepdbconf, since the 'conf' name has precedence.
