### ISSUE TITLE
Add license to bedfiles

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bbconf#51]
- [x] Add table of licenses.
- [x] Connect each bed record to a particular license.
- [x] Show this information in the BED metadata for each record. (ui)

**Comment by khoroshevskyi** [comment]
License table should look like:
name, url
cc-by-4.0,  https://creativecommons.org/licenses/by/4.0/
cc-by-nc-4.0, https://creativecommons.org/licenses/by-nc/4.0/

---
or : https://github.com/EBISPOT/DUO

**Comment by khoroshevskyi** [comment]
To find DUO license use this website: https://www.ebi.ac.uk/ols4/ontologies/duo

Have few questions:
- How to get metadata (annotation) about each class/ data use condition?
- How to restrict it in bedbase?

**Comment by nsheff** [comment]
just do this:

- allow us to annotate each bed file with one of these terms: https://github.com/EBISPOT/DUO/blob/master/duo.csv
- display which term is connected, on each bed and bedset page
- flag stuff from GEO as GRU by default; so everything will just be GRU for now.
- make bedboss able to use a different one, from an input pep that drives it.

**Comment by khoroshevskyi** [comment]
For db migration use this:
```
-- ALTER TABLE licenses
-- ADD CONSTRAINT unique_license_id UNIQUE (id);

ALTER TABLE bed
ADD COLUMN license_id CHARACTER VARYING;

ALTER TABLE bed
ADD CONSTRAINT fk_licese
FOREIGN KEY (license_id) REFERENCES licenses(id);

```
