### ISSUE TITLE
try making path  in paths:pipelines_output relative to the config file itself

### ISSUE THREAD

**Issue by stolarczyk** [databio/bbconf#7]
@joseverdezoto, the issue with `bedhost serve -c  bedbase_demo_PEPs/bedbase_configuration.yaml`  command stems from `bbconf` not making the config-sourced path  in `paths:pipelines_output` relative to the config file itself. I think you assumed that it does. So the solution is to change the config you use -- prepend `$HOME/bedbase_tutorial` to the path in the config.

_Originally posted by @stolarczyk in https://github.com/databio/bedhost/issues/14#issuecomment-606014199_

**Comment by xuebingjie1990** [comment]
@stolarczyk  I think this should be resolved?

**Comment by stolarczyk** [comment]
I'm not sure. Let's leave this open. I'll revisit bbconf later this week since some of the methods will need to be rewritten due to the switch to Postgres.

**Comment by khoroshevskyi** [comment]
This is an old issue as we are using new bbconf and bedboss
